CREATE TABLE contacts(
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    linkedin_id VARCHAR(255),
    linkedin_url VARCHAR(255),
    personal_email VARCHAR(255),
    location VARCHAR(255),
    country VARCHAR(255),
    company_id uuid,
    company_linkedin_id VARCHAR(255),
    company_name VARCHAR(255),
    company_domain VARCHAR(255),
    professional_email VARCHAR(255),
    mobile_phone VARCHAR(255),
    phone_numbers VARCHAR(255),
    title VARCHAR(255),
    seniority VARCHAR(255),
    department VARCHAR(255),
    email_verified BOOLEAN,
    email_confidence VARCHAR(255),
    email_verified_status VARCHAR(255),
    domain_age_days INTEGER,
    smtp_provider VARCHAR(255),
    mx_record VARCHAR(255))